clc;
A=[1 3 5;2 4 1;1 2 3];
printf("the matrix A is: \n");
disp(A);
S=sum(A);
printf("The sum of all entries of A is: ");
disp(S);
P=prod(A);
printf("The product of all entries of A is:");
disp(P);
B=sum(A,'c');
printf("The rowwise sum of A is: ");
disp(B);
C=sum(A,'r');
printf("The columwise sum of A is: ");
disp(C);
D=prod(A,'r');
printf("The columwise product of A is: ");
disp(D);
E=prod(A,'c');
printf("The rowwise product of A is: ");
disp(E);
